### ISSUE TITLE
Replace mvn with camel-jbang

### ISSUE THREAD

**Issue by mgubaidullin** [apache/camel-kameleon#26] opened 2022-08-06 15:18 UTC
@davsclaus 
As an idea. If we use camel-jbang instead of maven, perhaps it will be faster and requites less resources than maven

**Comment by davsclaus** [comment] 2022-08-07 08:12
Yeah that is a good idea, then its similar to karavan, and with jbang we have more a lot more power.
And we have synergy between kameleon and karavan.

**Comment by davsclaus** [comment] 2022-11-10 10:29
duplicate of #37

**Closed by davsclaus** 2022-11-10 10:29 UTC
